#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACMRT -- '*.go')
if [ -n "$STAGED_GO_FILES" ]; then
  go fmt $STAGED_GO_FILES
  git add $STAGED_GO_FILES
else
  echo "No Go files to update"
fi

failedTest() {
  STATUS=$?
  if [ $STATUS -eq 2 ]; then
    echo "The test failed. Check the test suite and try to commit again"
  fi

  exit 1
}

make test || failedTest

exit
